services:
  frontend:
    build: ./warhammer-battle-helper-front
    ports:
      - "3000:3000"
    restart: "no"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./warhammer-battle-helper-front:/app
      - /app/node_modules  # prevent overwriting node_modules
  backend:
    build:
      context: ./warhammer-battle-helper-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./warhammer-battle-helper-backend:/app
    env_file:
      - ./warhammer-battle-helper-backend/.env
    environment:
      - GIN_MODE=debug
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./warhammer-battle-helper-backend/mongo-data:/data/db

  admin:
    build: ./warhammer-battle-helper-admin
    ports:
      - "3001:3001"
    restart: "no"
    volumes:
      - ./warhammer-battle-helper-admin:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    restart: "no"

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
