// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Zwraca powitalne przesłanie",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "główne"
                ],
                "summary": "Strona główna",
                "responses": {
                    "200": {
                        "description": "Dzień dobry!!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/characters": {
            "get": {
                "description": "Pobiera listę wszystkich postaci z plików JSON",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Lista postaci",
                "responses": {
                    "200": {
                        "description": "Lista postaci w formacie JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error scanning directory",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Sprawdza stan zdrowia aplikacji",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Sprawdzenie stanu zdrowia",
                "responses": {
                    "200": {
                        "description": "Health is OK!!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Battle Helper API",
	Description:      "API do obsługi systemu Battle Helper",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
