basePath: /
host: localhost:8080
info:
  contact: {}
  description: API do obsługi systemu Battle Helper
  title: Battle Helper API
  version: "1.0"
paths:
  /:
    get:
      description: Zwraca powitalne przesłanie
      produces:
      - text/plain
      responses:
        "200":
          description: Dzień dobry!!
          schema:
            type: string
      summary: Strona główna
      tags:
      - główne
  /characters:
    get:
      description: Pobiera listę wszystkich postaci z plików JSON
      produces:
      - application/json
      responses:
        "200":
          description: Lista postaci w formacie JSON
          schema:
            type: string
        "500":
          description: Error scanning directory
          schema:
            type: string
      summary: Lista postaci
      tags:
      - characters
  /health:
    get:
      description: Sprawdza stan zdrowia aplikacji
      produces:
      - text/plain
      responses:
        "200":
          description: Health is OK!!
          schema:
            type: string
      summary: Sprawdzenie stanu zdrowia
      tags:
      - health
swagger: "2.0"
