export const WS_EVENTS = {
  // Game state
  GAME_STATE:         'GAME_STATE',
  GAME_DELETED:       'GAME_DELETED',
  GAME_IMAGE_UPDATED: 'GAME_IMAGE_UPDATED',

  // Participants
  PARTICIPANT_JOINED:  'PARTICIPANT_JOINED',
  PARTICIPANT_LEFT:    'PARTICIPANT_LEFT',
  PARTICIPANT_UPDATED: 'PARTICIPANT_UPDATED',
  USERS_ONLINE:        'USERS_ONLINE',

  // Characters (grid)
  CHARACTER_ADDED:              'CHARACTER_ADDED',
  CHARACTER_MOVED:              'CHARACTER_MOVED',
  CHARACTER_REMOVED:            'CHARACTER_REMOVED',
  CHARACTER_UPDATED:            'CHARACTER_UPDATED',
  CHARACTER_VISIBILITY_UPDATED: 'CHARACTER_VISIBILITY_UPDATED',

  // Rolls
  DICE_ROLLED:   'DICE_ROLLED',
  SKILL_ROLLED:  'SKILL_ROLLED',
  WEAPON_ROLLED: 'WEAPON_ROLLED',

  // Messages
  LOG_MESSAGE: 'LOG_MESSAGE',

  // Handouts
  HANDOUT_CREATED:          'HANDOUT_CREATED',
  HANDOUT_UPDATED:          'HANDOUT_UPDATED',
  HANDOUT_DELETED:          'HANDOUT_DELETED',
  HANDOUT_MOVED:            'HANDOUT_MOVED',
  HANDOUTS_REORDERED:       'HANDOUTS_REORDERED',
  HANDOUT_FOLDER_CREATED:   'HANDOUT_FOLDER_CREATED',
  HANDOUT_FOLDER_UPDATED:   'HANDOUT_FOLDER_UPDATED',
  HANDOUT_FOLDER_DELETED:   'HANDOUT_FOLDER_DELETED',
  HANDOUT_FOLDERS_REORDERED: 'HANDOUT_FOLDERS_REORDERED',

  // Scenes
  SCENE_CREATED:      'SCENE_CREATED',
  SCENE_UPDATED:      'SCENE_UPDATED',
  SCENE_DELETED:      'SCENE_DELETED',
  PLAYER_SCENE_CHANGED: 'PLAYER_SCENE_CHANGED',

  // Scene characters
  SCENE_CHARACTER_ADDED:   'SCENE_CHARACTER_ADDED',
  SCENE_CHARACTER_MOVED:   'SCENE_CHARACTER_MOVED',
  SCENE_CHARACTER_REMOVED: 'SCENE_CHARACTER_REMOVED',

  // Scene images
  SCENE_IMAGE_ADDED:         'SCENE_IMAGE_ADDED',
  SCENE_IMAGE_UPDATED:       'SCENE_IMAGE_UPDATED',
  SCENE_IMAGE_DELETED:       'SCENE_IMAGE_DELETED',
  SCENE_IMAGE_TOKEN_UPDATED: 'SCENE_IMAGE_TOKEN_UPDATED',

  // Fog of war
  FOG_TOGGLED:      'FOG_TOGGLED',
  FOG_PATH_ADDED:   'FOG_PATH_ADDED',
  FOG_PATH_REMOVED: 'FOG_PATH_REMOVED',
  FOG_CLEARED:      'FOG_CLEARED',
  FOG_REVEALED_ALL: 'FOG_REVEALED_ALL',

  // Notes
  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_DELETED: 'NOTE_DELETED',

  // Drawing
  DRAWING_PATH_ADDED:   'DRAWING_PATH_ADDED',
  DRAWING_PATH_REMOVED: 'DRAWING_PATH_REMOVED',
  DRAWING_CLEARED:      'DRAWING_CLEARED',

  // Music
  MUSIC_PLAY:   'MUSIC_PLAY',
  MUSIC_PAUSE:  'MUSIC_PAUSE',
  MUSIC_STOP:   'MUSIC_STOP',
  MUSIC_VOLUME: 'MUSIC_VOLUME',
  MUSIC_LOOP:   'MUSIC_LOOP',

  // Token display config (per-user singleton, resolve-on-read)
  TOKEN_CONFIG_UPDATED: 'TOKEN_CONFIG_UPDATED',

  // Pointer
  POINTER_PING: 'POINTER_PING',

  // Minigames
  MINIGAME_STARTED:       'MINIGAME_STARTED',
  MINIGAME_STATE_UPDATED: 'MINIGAME_STATE_UPDATED',
  MINIGAME_ENDED:         'MINIGAME_ENDED',
};
